# Generated by Django 3.1.1 on 2021-04-28 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopprofile',
            name='gender',
            field=models.CharField(choices=[('monthly', 'Monthly'), ('yearly', 'Yearly')], default='yearly', max_length=8),
        ),
    ]
