# Generated by Django 3.1.1 on 2021-04-28 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_shopprofile_gender'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shopprofile',
            old_name='gender',
            new_name='subscription',
        ),
    ]
