# Generated by Django 3.1.1 on 2021-04-28 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20210428_1304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopprofile',
            name='updated',
            field=models.DateField(auto_now=True),
        ),
    ]
