# Generated by Django 3.1.1 on 2021-04-28 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20210428_1318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopprofile',
            name='subscription',
            field=models.CharField(choices=[('monthly', 'Monthly'), ('yearly', 'Yearly')], default='yearly', help_text='Pay monthly or yearly?', max_length=8),
        ),
    ]
