# Generated by Django 3.1.1 on 2021-05-02 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20210428_1330'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopprofile',
            name='shop_package',
            field=models.CharField(choices=[('standard', 'Standard'), ('advanced', 'Advanced'), ('premium', 'Premium')], default='standard', help_text='Standard = 100 products, Advanced=200 products,Premium=Above 200 products', max_length=9),
        ),
    ]
