# Generated by Django 3.1.1 on 2021-04-29 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20210428_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='old_cost',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10),
        ),
    ]
